# Site settings
title: Full Image Manager
email: natasaborovcanin@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Full Image Manager is an OpenCart extension based on elFinder. with very powerful options and user friendly interface.
baseurl: "/full-image-manager" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: natasaborovcan2
github_username:  natasaborovcanin

# Build settings
markdown: kramdown
